const languages = {
	English: "En",
	German: "De",
	Deutsch: "De",
	'Deutsch / Deutsch': "De",
	Japanese: "Ja",
	Polish: "Pl",
	Magyar: "Hu",
	Espanol: "Es",
	Russian: "Ru",
	Czech: "Cz",
	Arabic: "Ar",
	French: "Fr",
	'Keine Angabe / Deutsch': "De",
	Spanish: "Es",
	Portuguese: "Pt",
	Italian: "It",
	Hungarian: "Hu",
	Slovak: "Sk",
	'English / English': "En",
	Korean: "Ko",
	Unknown: "",
	new: "",
	Hindi: "Hi",
	'Multiple languages': "",
	Swedish: "Sv",
	Romanian: "Ro",
	Turkish: "Tr",
	Chinese: "Zh",
	Greek: "Gr",
	Indonesian: "In",
	Norwegian: "No",
	Hebrew: "He",
	Ukrainian: "Ua",
	Estonian: "Et",
	Latvian: "Lv",
	Lithuanian: "Lt",
	Dutch: "Nl",
	Danish: "Da",
	Finnish: "Fi",
	Thai: "Th",
	Bulgarian: "Bg",
	'Norwegian Bokmal': "No",
	Croatian: "Hr",
	Icelandic: "Is",
	Serbian: "Sr",
	Slovenian: "Sl",
	Vietnamese: "Vi",
	Malay: "Ms"
}

export {
	languages
}