const languages = {
	English: "En",
	German: "De",
	Deutsch: "De",
	'Deutsch / Deutsch': "De",
	Japanese: "Ja",
	Polish: "Pl",
	Magyar: "Hu",
	Espanol: "Es",
	Russian: "Ru",
	Czech: "Cz",
	Arabic: "Ar",
	French: "Fr",
	'Keine Angabe / Deutsch': "De",
	Spanish: "Es",
	Portuguese: "Pt",
	Italian: "It",
	Hungarian: "Hu",
	Slovak: "Sk",
	'English / English': "En",
	Korean: "Ko",
	Unknown: "",
	new: "",
	Hindi: "Hi",
	'Multiple languages': "",
	Swedish: "Sv",
	Romanian: "Ro",
	Turkish: "Tr",
	Chinese: "Zh",
	Greek: "Gr",
	Indonesian: "In",
	Norwegian: "No",
	Hebrew: "He",
	Ukrainian: "Ua",
	Estonian: "Et",
	Latvian: "Lv",
	Lithuanian: "Lt",
	Dutch: "Nl",
	Danish: "Da",
	Finnish: "Fi",
	Thai: "Th",
	Bulgarian: "Bg",
	'Norwegian Bokmal': "No",
	Croatian: "Hr",
	Icelandic: "Is",
	Serbian: "Sr",
	Slovenian: "Sl",
	Vietnamese: "Vi",
	Malay: "Ms"
}

const languageKeys = {
	De: "German",
	En: "English",
	Ja: "Japanese",
	Pl: "Polish",
	Hu: "Hungarian",
	Es: "Spanish",
	Ru: "Russian",
	Cz: "Czech",
	Ar: "Arabic",
	Fr: "French",
	Pt: "Portuguese",
	It: "Italian",
	Sk: "Slovak",
	Ko: "Korean",
	Hi: "Hindi",
	Sv: "Swedish",
	Ro: "Romanian",
	Tr: "Turkish",
	Zh: "Chinese",
	Gr: "Greek",
	In: "Indonesian",
	No: "Norwegian",
	He: "Hebrew",
	Ua: "Ukrainian",
	Et: "Estonian",
	Lv: "Latvian",
	Nl: "Dutch",
	Da: "Danish",
	Fi: "Finnish",
	Th: "Thai",
	Bg: "Bulgarian",
	Hr: "Croatian",
	Is: "Islandic",
	Sr: "Serbian",
	Sl: "Slovenian",
	Vi: "Vietnamese",
	Ms: "Malay"
}

export {
	languages,
	languageKeys
}